craigslist/config/routes.rb
Rails.application.routes.draw do
  # get '/' => "application#index"
  get '/articles/:id/success' => 'articles#success'
  get '/articles/:id/:key' => 'articles#edit'

  resources :articles, :categories
  root to: "categories#index"
end

craigslist/app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :category
end

craigslist/app/models/category.rb
class Category < ActiveRecord::Base
  has_many :articles
end

craigslist/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def index
  end
end

craigslist/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def show
    @article = Article.find(params[:id])
  end

  def new
    @category_options = Category.all.map{|c| [ c.title, c.id ] }
    @article = Article.new
  end

  def create

    @article = Article.new(article_params)
    if @article.valid?
      @article.key = create_key
      @article.save
    end
    redirect_to "/articles/#{@article.id}/success"
  end

  def edit
    @article = Article.find(params[:id])
      if @article.key == params[:key]
       @category_options = Category.all.map{|c| [ c.title, c.id ] }
       edit_article_path(@article)

      else
        redirect_to article_path(@article)
      end
  end

  def update
    @article= Article.find(params[:id])
    @article.update_attributes(article_params)
    @category = @article.category
    redirect_to category_path(@category)
  end

  def destroy
    @article= Article.find(params[:id])
    @category = @article.category
    @article.destroy
    redirect_to category_path(@category)
  end

  def success
    @article = Article.find(params[:id])
  end

   private

   def article_params
      params.require(:article).permit(:title, :description, :price, :category_id)
   end

  def create_key
    @key = Faker::Internet.password(8)
    return @key
  end
end

craigslist/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end
end

craigslist/app/helpers/application_helper.rb
module ApplicationHelper
end

craigslist/app/views/articles/edit.html.erb
<h1>Edit your article</h1>


<%= form_for @article, url: {action: "update"}, method: "PUT" do |f| %>
<p><%= f.text_field :title,  value: @article.title %></p>
<p><%= f.text_area :description, size: "60x12", value: @article.description %></p>
<p><%= f.text_field :price , value: @article.price %></p>
<p><%= f.text_field :email , value: @article.email %></p>
<p><%= f.select :category_id, options_for_select(@category_options) %></p>
  <%= f.submit "Edit Article" %>
<% end %>

<%=link_to 'Delete Article', article_path, :method => :delete%>

craigslist/app/views/articles/new.html.erb
<h1>Add a new article</h1>


<%= form_for @article, url: {action: "create"} do |f| %>
<p><%= f.text_field :title,  placeholder: 'Title'%></p>
<p><%= f.text_area :description, size: "60x12", placeholder: "Enter your description here" %></p>
<p><%= f.text_field :price , placeholder: "Price"%></p>
<p><%= f.text_field :email , placeholder: "Email Address"%></p>
<p><%= f.select :category_id, options_for_select(@category_options) %></p>
  <%= f.submit "Create Article" %>
<% end %>

craigslist/app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
    <ul>
      <li> <%= @article.description%></li>
      <li><%= @article.price%></li>
      <li><%= @article.email%></li>
    </ul>

<h3><%=link_to @article.category.title, category_path(@article.category)%></h3>

craigslist/app/views/articles/success.html.erb
<h1> Your article was posted successfully </h1>
<h2> To edit your article, you will need to use the following link</h2>

<a href="/articles/<%=@article.id%>/<%=@article.key%>">
  /articles/<%=@article.id%>/<%=@article.key%></a>

craigslist/app/views/categories/index.html.erb
<h1>All Categories</h1>

<ul>
  <% @categories.each do |category| %>
    <li><%= link_to category.title, category_path(category) %>
    </li>
  <%end%>
</ul>

<li><%= link_to "Post a new Article", new_article_path%> </li>

craigslist/app/views/categories/show.html.erb
<h1><%=@category.title%></h1>

  <%@category.articles.each do |article|%>
    <ul>
      <li><%=link_to article.title, article_path(article) %></li>
    </ul>
  <%end%>

  <%= link_to "Post a new Article", new_article_path%><br>

  <%= link_to "All categories", categories_path %>

craigslist/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Craigslist</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>